[package]
name = "service"
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
version = "0.1.3"
=======
version = "0.1.2"
>>>>>>> b7d1328 (Cargo update)
=======
version = "0.1.3"
>>>>>>> f0184d8 (aligned integration test to new transaction format)
=======
version = "0.1.4"
>>>>>>> 922c20d (updated all contracts)
authors = ["The Trinci Team <trinci@affidaty.io>"]
edition = "2021"
description = "Basic node service"

[lib]
crate-type = ["cdylib"]

[dependencies]
trinci-sdk = { git = "https://github.com/affidaty-blockchain/trinci-sdk-rust" }
serde = "1.0.126"
serde_derive = "1.0.126"
serde_bytes = "0.11.5"
hex = "0.4.3"
sha256 = "1.0.2"

[dev-dependencies]
hex = "0.4.3"
