[package]
name = "pay-meal"
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
version = "0.1.2"
=======
version = "0.1.1"
>>>>>>> b7d1328 (Cargo update)
=======
version = "0.1.2"
>>>>>>> f0184d8 (aligned integration test to new transaction format)
=======
version = "0.1.3"
>>>>>>> 922c20d (updated all contracts)
authors = ["The Trinci Team <trinci@affidaty.io>"]
edition = "2021"
description = "Contract from the Trinci SDK Tutorial"

[lib]
crate-type = ["cdylib"]

[dependencies]
trinci-sdk = { git = "https://github.com/affidaty-blockchain/trinci-sdk-rust" }
serde = "1.0.126"
serde_derive = "1.0.126"

[dev-dependencies]
hex = "0.4.3"
